### PR TITLE
LPS 143574

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
@mbowerman 
I used DELETE for the getActionDropdownItems() because it only has the option delete in the menu.

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Forwarded to Lima team: https://github.com/liferay-lima/liferay-portal/pull/2545

**Pull request closed without merging**
