### PR TITLE
Lps 143395

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Hi @javalosjr96,

I don't think this is the proper fix.

The problem with this fix, is that the results aren't filtered until _after_ the main search operation has occurred, which includes the pagination. So, if you have more Groups than the default page size, it can cause the pagination to become messed up.

Also, you are overriding the `total` with only the total of the filtered results on the page, rather than having it as the total of all results across all pages, which is what it was before.

Let me give an example:
1. Add 40 Child sites to the default Liferay Site (it may take a while to do this manually, maybe you can find or modify a script from https://github.com/liferay/liferay-support-ee/tree/master/scripts to help with this).
2. Set the membership options to all of the sites to private.
3. Create a new user and assign them to about 20 of the Child sites. Try to assign them to a random 20 Child sites rather than just picking the first 20 that were created.
4. Log into the new user.
5. Navigate to the My Sites Widget and click on the "x Child Sites" link underneath the Liferay Site.
Expected result: It would display all 20 child sites that the user is a member of.
Actual result: It only displays a random subset of the 20 child sites, and only lists that number as the total. This is because you got the first 20 sites independent of permissions, and then filtered them down afterwards (some passed the permission check, and others didn't).

Here's another example of just the issue with `total`, which is much simpler to test:
1. Add enough sites until you have 21 sites total.
2. Navigate to the My Sites Widget.
Expected result: It would say "Showing 1 to 20 of 21 entries" at the bottom.
Actual result: It says "Showing 1 to 20 of 20 entries" at the bottom. Also if you navigate to the second page, it would then say "Showing 21 to 21 of 1 entry" (at least I think it would, I'm not 100% sure about how this logic works).

The proper fix for this is to fix the permissioning issue in the group searching logic itself inside of GroupFinderImpl or GroupLocalServiceImpl. That way we can maintain correct pagination when the user has enough Groups to require pagination.

**Comment by javalosjr96** [comment]
@mbowerman Ok

**Pull request closed without merging**
