### PR TITLE
LPS-64043

### PR DESCRIPTION
**Pull request by topolik**
Hi @mbowerman,

I fixed permission checking. The idea is correct but there were some bugs.

I didn't test it, please can you retest to make sure it's doing what you'd expect?

Thanks!

/cc @juliocamarero

### CODE REVIEW

**Comment by mbowerman** [comment]
Looks good, I should note that when I tested it, I got an UnsupportedOperationException when viewing the page as the logged in user, but I'm 99.9% sure that's because I was using my old database which wasn't rebased to the version of Liferay you're using, as I got the same exception even when viewing pages that didn't have categories navigation portlets.

**Comment by topolik** [comment]
Thanks. Please can you also test it on a fresh master to be sure it's working?

The changes in `AdvancedPermissionChecker` can create regressions we should avoid.

**Comment by mbowerman** [comment]
I rebased it on top of the latest version of master and tested it with a fresh database. Everything worked as expected. I did not see any errors in the console, either.

**Comment by topolik** [comment]
Perfect. Feel free to send it to Brian. Or tell me if you want me to. Thanks.

**Comment by mbowerman** [comment]
Could you please send it to him, if you don't mind? Thanks.

**Comment by topolik** [comment]
Done. Please see
https://github.com/brianchandotcom/liferay-portal/pull/37549

-- tom +

**Pull request closed without merging**
