### PR TITLE
LPS-185647 Flush in DB Partition

### PR DESCRIPTION
**Pull request by achaparro**
- LPS-185647 Add support to push and pop companies
- LPS-185647 Add Listeners to set companyId as appropriate before and after writing an entity to the database
- LPS-185647 Register the new listeners if db partitioning is enabled
- LPS-185647 Use append instead of set here since we are registering POST_UPDATE EventListeners from multiple places now, and there is no guarantee on which order they will be registered in
- LPS-185647 Semantic versioning
- LPS-185647 In DB partition every partition has its own basic document type
- LPS-185647 Let's execute the pop company after the pre event and before going to the database. This prevents having an incorrect companyThreadLocal when the post event is not executed if the SQL operations fails and I guess it also improves the performance.

### CODE REVIEW

**Comment by achaparro** [comment]
Hi @mbowerman,

I fixed the issue with the BASIC_DOCUMENT, I think it is safe since we never use the companyId to retrieve the object, it also makes sense since in DB Partition there is one BASIC_DOCUMENT per partition. We may need an upgrade to se the companyId in existing db partitioning environments.

I also moved the pop operation to the DBPartitionUtil to always pop even when the statement fails.

I tested the SAP issue with my existing database and it is working. However I was doing additional testing and I got an issue creating new virtual instances:

>  2023-06-21 09:10:49.388 ERROR [http-nio-8080-exec-8][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '33952-0-imageVariants-0' for key 'PortletPreferenceValue.IX_AD38E28D'], SQL: insert into PortletPreferenceValue (mvccVersion, ctCollectionId, companyId, portletPreferencesId, index_, largeValue, name, readOnly, smallValue, portletPreferenceValueId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
> 2023-06-21 09:10:49.390 ERROR [http-nio-8080-exec-8][SqlExceptionHelper:142] Duplicate entry '33952-0-imageVariants-0' for key 'PortletPreferenceValue.IX_AD38E28D'

Which is weird since this is the index:
 create unique index IX_AD38E28D on PortletPreferenceValue (portletPreferencesId, index_, name, ctCollectionId);
 
 And I put a conditional breakpoint in the preInsert event only for PortletPreferenceValue I get two entities:
```
  _mvccVersion = 0
_ctCollectionId = 0
_portletPreferenceValueId = 132
_companyId = 33950
_portletPreferencesId = 33952
_index = 0
_largeValue = null
_name = "imageVariants"
_readOnly = false
_smallValue = "Preview+1000x0:This+image+resolution+was+automatically+added.:Preview-1000x0:max-height=0;max-width=1000:enabled=true"
_columnOriginalValues = {Collections$EmptyMap@51482}  size = 0
_columnBitmask = 0
_escapedModel = null
_cachedModel = false
_new = false
```
And:
```
 _mvccVersion = 0
 _ctCollectionId = 0
 _portletPreferenceValueId = 133
 _companyId = 33950
 _portletPreferencesId = 33952
 _index = 1
 _largeValue = null
 _name = "imageVariants"
 _readOnly = false
 _smallValue = "Thumbnail+300x300:This+image+resolution+was+automatically+added.:Thumbnail-300x300:max-height=300;max-width=300:enabled=true"
 _columnOriginalValues = {Collections$EmptyMap@51482}  size = 0
 _columnBitmask = 0
 _escapedModel = null
 _cachedModel = false
 _new = false
```
 
 You can see that the index is 0 and 1 so the index should not being violated but it happens, can you verify if you reproduce this issue?
 
 Thanks.

**Comment by mbowerman** [comment]
Hey @achaparro, I tested your fix and I didn't get the exact error that you mentioned; however, I got a similar error when creating a new virtual instance:
```
2023-06-21 15:50:25.826 ERROR [http-nio-8080-exec-7][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '0-0' for key 'dlfileentrytype.PRIMARY'], SQL: insert into DLFileEntryType (mvccVersion, ctCollectionId, uuid_, groupId, companyId, userId, userName, createDate, modifiedDate, dataDefinitionId, fileEntryTypeKey, name, description, scope, lastPublishDate, fileEntryTypeId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2023-06-21 15:50:25.831 ERROR [http-nio-8080-exec-7][SqlExceptionHelper:142] Duplicate entry '0-0' for key 'dlfileentrytype.PRIMARY'
```
I am investigating it now.

Update: It seems to be committing it against the main partition, instead of against the new partition. I assume that the error you got is occurring for the same reason. Looking into that now.

**Comment by achaparro** [comment]
Hey @mbowerman,

The error you are getting seems related to the creation of the BASIC_DOCUMENT type, I didn't get that issue and I verified it but maybe somehow we are getting weird race conditions :-(

**Comment by mbowerman** [comment]
Ah sorry @achaparro, I just realized that I was testing incorrectly. I only tested by cherry-picking your two latest commits on top of my existing branch, but now I realize that you had modified the first commit as well (which I didn't bring into my branch). I will compile your whole branch and then re-test.

**Comment by mbowerman** [comment]
Hi @achaparro ,

Now I am reproducing the same error that you saw and I will start investigating it.

**Comment by mbowerman** [comment]
Hey @achaparro I think the push and pop may not be working correctly. It seems to be always reverting the CompanyThreadLocal to 0 when you call `popCompanyId`, instead of reverting it to what it was previously. I will double-check it and work on a fix for it.

**Comment by mbowerman** [comment]
Hey @achaparro I fixed the push/pop issue and now I can add Virtual Instances successfully without any errors. I will test the other bugs as well.

Update: Verified that [LPS-184771](https://liferay.atlassian.net/browse/LPS-184771) is fixed.

**Comment by achaparro** [comment]
Marvelous @mbowerman!

**Comment by achaparro** [comment]
If you get a complete solution today, please, send a pull to the uniform repo so QA can monitor it. If not, you can send it to me and I will work on it tomorrow.

Thank you so much @mbowerman

**Comment by mbowerman** [comment]
Hey @achaparro, everything seems to be working correctly so I have sent the pull request to the liferay-uniform user as you said: https://github.com/liferay-uniform/liferay-portal/pull/1236

Thanks again for all your hard work on this issue!

**Pull request closed without merging**
