### PR TITLE
LPS-74083

### PR DESCRIPTION
**Pull request by hhuijser**

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:reopen

**Comment by mbowerman** [comment]
Hey guys @yuhai @hhuijser,

This fix doesn't seem correct to me. The issue is that the content processor assumes that the site you will be importing to is identical to the site you are exporting from (at least in terms of page structure). This fix acts like a band-aid for this one particular use case, but what about the following use cases?

1. You try to import the web content onto a new database in which Site1 has been imported, but with a different groupId than Site1 had on the old database.
2. The web content has a link to a page on its own site, and you export it into a different site.

I have not tested these cases, but I believe that this fix would break case 1 (exporting and importing between databases) even more than it was already, because we are just appending the groupId, when the groupId can be different between databases. And it would not fix case 2, because of the if condition that you included, which I don't really understand the logic behind.

I think the correct fix is to modify the behavior of the processor so that when the web content is exported, it appends the uuid of the urlGroup to `@data_handler_group_friendly_url@`. This way, the correct Group can be looked up and appended to the url when we import the web content. If we do this, we may also need to add some logic to the missing references validator, but I'm not sure about this.

Let me know if you disagree with my analysis. If not, please let me know if one of you has time to work on the fix I proposed, or if you'd prefer me to work on it instead.

**Comment by yuhai** [comment]
Hi @mbowerman ,

Thanks for your response.

I want to explain the fix behavior.

In my opinion, the **expected design behavior** is as the following:
Site1(Export site): exist one layout:testPage, create one web content, its content includes:
`<a href="http://localhost:8080/web/site1/testpage">link</a>`

Site2(Import target site): After import site1.lar to Site2, the web content should be: 
`<a href="http://localhost:8080/web/site2/testpage">link</a>. `
In target site2, it should change site1 for site2 because export/import is the copy process. Instead of the link still linked the original site1. This will work between different database.

Based the above my understanding, I will answer you mentioned questions.

> 1.You try to import the web content onto a new database in which Site1 has been imported, but with a different groupId than Site1 had on the old database.
> 2. The web content has a link to a page on its own site, and you export it into a different site.

For two cases, on new database, the link should be changed for target site. The fix is based on above understanding.

**Why do I think?**
For example ,
case1: 
database1: site1. One web content's content included the content:
`<a href="http://ip1:8080/web/site1/testpage">link</a>`

database2: siet2. After import, if we keep the same content:
`<a href="http://ip1:8080/web/site1/testpage">link</a>`

When application server with database1 is down or site1 was deleted , for site2 of database1, this link won't be displayed (miss reference).

case2:
When enable staging:
In staging site: the web content link own site page(stagingSite: page1).
In live site: the web content link should link live site page (liveSite: page1) after publish to live.

>  it appends the uuid of the urlGroup to @data_handler_group_friendly_url@. This way, the correct Group can be looked up and appended to the url when we import the web content

I think this way can't work on two different database. For example:
Database1 Site1 (uuid=1******), Database2 Site2(uuid=2*******). After import site1 to site2, site1 uuid doesn't existed in database2, so this is one issue.

In addition, I think the above mentioned is related with the behavior without the fix. Actually, **the fix focused on** " when exportLayoutReferences's group (DXP site) is not current group(group:Site1), we should keep its group. Otherwise, when import it to targetGroup (group: Site2), it will be replaced with targetGroup(Site2). Please refer to the explanation from https://github.com/hhuijser/liferay-portal/pull/2968#issue-250579679 

Please kindly let me know if my understanding is not right.

Regards,
Hai

**Comment by mbowerman** [comment]
Hi @yuhai,

Yes, I think you are right about case 2. My apologies, I had thought that we use the uuid to match staging groups to live groups the same way we do for other staged content, but we don't. And we should be able to assume that the groupFriendlyURL is the same.

I am still not sure about case 1. It is unclear to me what the intended behavior should be in this case. There could be two possibilities for the intended behavior:

1. The behavior you described, where if the link is a link of the same site it is exported from, we assume that the imported link should go to the site that you linked to.
2. The link is treated as an absolute link, and will always link to the site that it originally linked to when it was exported.

I am not sure which of these cases is the intended behavior, and I think an argument could be made for either one. Perhaps the (1) behavior could be used as the default, and then the (2) behavior could be used if we determine that (1) behavior would lead to an invalid link on importing? I will forward the pull to @matethurzo to get his thoughts.

**Comment by mbowerman** [comment]
Pull request forwarded to @matethurzo: https://github.com/matethurzo/liferay-portal/pull/1719

**Pull request closed without merging**
