### PR TITLE
LPS-152785v3

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
https://issues.liferay.com/browse/LPS-152875

Previous PR:
https://github.com/mbowerman/liferay-portal/pull/122

Description:
In order to be able to update org.json, changes needed to be made in two areas:
1. The current jabsorb needed to be modified to allow the usage of `BigDecimal`.
2. Added the positive character to the list operators to the json parser account for positive scientific notation.

### CODE REVIEW

**Comment by javalosjr96** [comment]
@mbowerman
JSONFactoryTest passed locally

The only concern that I have are the commits for the patch jabsorb jar. 
LMK if any commits need to be squash or if the commit message needs to be changed.

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:stable

**Comment by mbowerman** [comment]
Pull request forwarded to https://github.com/liferay-core-infra/liferay-portal/pull/829

**Pull request closed without merging**
