### PR TITLE
LPS 137856v2

### PR DESCRIPTION
**Pull request by javalosjr96**
Previous fix was rebased to a more recent version of master to try to get the regression bugs to occur.
Both LPS-138269 and LPS-138244 failed to occur.
Resubmitting original fix.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Doesn't look like a relevant test failure. Let's wait to see how QA responds.

**Comment by mbowerman** [comment]
Pull request forwarded to Echo team for further review: https://github.com/liferay-echo/liferay-portal/pull/5834

**Pull request closed without merging**
