### PR TITLE
Lps 163136 nov4

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Sent pull request to fix SF error here: https://github.com/brianchandotcom/liferay-portal/pull/125819

**Comment by mbowerman** [comment]
Pull request forwarded to Core Infrastructure team: https://github.com/liferay-core-infra/liferay-portal/pull/2352

**Pull request closed without merging**
