### PR TITLE
Lps 141974

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
@mbowerman 
I changed it to DUPLICATE.

**Comment by mbowerman** [comment]
Pull request forwarded to https://github.com/liferay-echo/liferay-portal/pull/6408

I made some more changes to the Test class, you can see them at https://github.com/liferay-echo/liferay-portal/compare/9a52a247879e6001374862ec0ef5343004540476...bfc24a9d2b8803cb5d2d2890b33a139ebaea551d

**Pull request closed without merging**
