### PR TITLE
LPS-151328 Added getLocale method and modified method of passing loca

### PR DESCRIPTION
**Pull request by SelenaAungst**
le to getName function to use user locale if possible.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
Pull request forwarded to https://github.com/liferay-objects/liferay-portal/pull/577

**Pull request closed without merging**
