### PR TITLE
Lps 152875v2

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
It seems that the latest org.json:json library now parses decimal strings as the `BigDecimal` class instead of the `double` by default (see the relevant commit here: https://github.com/stleary/JSON-java/commit/56d33b806139ac5d69b1b7ff00952f01605e09ed).

We could easily update the [FooBean5](https://github.com/liferay/liferay-portal/blob/master/portal-impl/test/unit/com/liferay/portal/json/FooBean5.java) class to use BigDecimal instead of double to fix the JSONFactoryTest failures. However, it seems likely that this switch from double to BigDecimal may potentially cause other issues throughout the portal, given how widely the json library is used.

I've reached out to Angelo to ask how we should handle this.

**Comment by javalosjr96** [comment]
@mbowerman I'm guessing that the case is the same for FooBean3.

**Comment by jeffwu0724** [comment]
@mbowerman Hey Michael, may I ask if there is any update on this, please? Thanks for your reply!

**Comment by mbowerman** [comment]
@jeffwu0724 We discussed this amongst ourselves on Slack. @javalosjr96 is going to work on making a modification to the third-party jabsorb .jar that we expect will safely resolve the test failures and prevent the json upgrade from introducing regressions.

**Comment by jeffwu0724** [comment]
> @jeffwu0724 We discussed this amongst ourselves on Slack. @javalosjr96 is going to work on making a modification to the third-party jabsorb .jar that we expect will safely resolve the test failures and prevent the json upgrade from introducing regressions.

Great, thank you very much Michael for your update!

**Pull request closed without merging**
