### PR TITLE
LPS-185647 DB Partition: flush the session per company when iterating companies and having a single transaction.

### PR DESCRIPTION
**Pull request by achaparro**
- LPS-185647 When iterating companies and a transaction is opened we must flush the modifications for every company before executing the commit in the original company
- LPS-185647 Do nothing when db partition is not enabled

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:stable

**Comment by achaparro** [comment]
ci:test:dp-partitio

**Comment by achaparro** [comment]
ci:test:dp-partition

**Comment by achaparro** [comment]
ci:test:db-partition

**Comment by mbowerman** [comment]
Thank you @achaparro! I tested your fix. It seems to fix [LPS-185647](https://issues.liferay.com/browse/LPS-185647) but not [LPS-184771](https://issues.liferay.com/browse/LPS-184771). I'm guessing that the reason it does not fix [LPS-184771](https://issues.liferay.com/browse/LPS-184771) is because in that bug, the code is calling "executeAsCompany" rather than "forEachCompanyId". So, we likely just need to apply the same logic to the "executeAsCompany" method. I will test this hypothesis a little later.

**Comment by achaparro** [comment]
Thanks a lot @mbowerman !

**Comment by mbowerman** [comment]
Hello @achaparro,

Unfortunately after further investigation, it seems that this approach will not work in the general case.

This is because the *Persistence classes in different modules have different Session objects attached to them.

For [LPS-185647](https://issues.liferay.com/browse/LPS-185647), this approach works well, because ResourcePermissionPersistence is in the same module as CompanyPersistence (portal-impl), so both of them have the same session object. So when we flush the CompanyPersistence session, it flushes the ResourcePermission session (as they are the same session).

However, the same approach does not work for [LPS-184771](https://issues.liferay.com/browse/LPS-184771). If we flush the CompanyPersistence session, it doesn't really accomplish anything, because the session we need to flush is the SAPEntryPersistence session, which is a different session (as SAPEntryPeresistence belongs to a different module than CompanyPersistence).

I'm not sure what the best way to handle this is. I suppose maybe we could add new APIs in CompanyLocalServiceImpl that can take in Supplier<Session> as an argument (also in ConfigurationFactoryUtil which is the one that is relevant to [LPS-184771](https://issues.liferay.com/browse/LPS-184771). However, I worry that this could get a bit ugly/confusing, and that most people wouldn't understand the purpose of the Supplier<Session> argument. What do you think?

**Comment by achaparro** [comment]
Hi @mbowerman,

I agree, i guess the supplier could be confusing.

I was testing the SAP issue and it is slightly different. In this case we are in the scope of the uat company and just because the configuration module is activated, we switch the CompanyThreadLocal. When we are in a specific company scope we should not switch to another except for control tables like ResourceAction as it happened in the other ticket.

We have two options here:
- Analyze if it possible to not run the activate in this case. I am not sure if this is required.
- Somehow run the flush when we change the CompanyThreaLocal inside a transaction. This can solve all future problems but I am not sure how to get the current session in this case.

I could not invest so much time on this since I am sick :-(

**Comment by mbowerman** [comment]
> - Somehow run the flush when we change the CompanyThreaLocal inside a transaction. This can solve all future problems but I am not sure how to get the current session in this case.

Oh yeah, I forgot to mention that I tried this approach as well earlier. And I came to the same conclusion as you. It doesn't seem to be possible to get the current session in CompanyThreadLocal because portal-kernel does not have visibility into the Hibernate or Spring code..

**Comment by mbowerman** [comment]
Hey @achaparro,

One thought that I had is that we could possibly add a new `ThreadLocal` like `HibernateSessionThreadLocal` to track all the active sessions in the thread. However, this is starting to veer into Core Infra territory, and this may be difficult to implement effectively. 

If we are able to implement this, then we could reference this `ThreadLocal` from within the `CompanyThreadLocal` to flush all the active sessions before changing the companyId. What do you think about this?

**Comment by achaparro** [comment]
Hey @mbowerman,

We need something like that although I am trying to simplify the approach. Analyzing the hibernate code a possible solution could be to wrap the Hibernate session here:
https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/dao/orm/hibernate/SessionImpl.java#L388

So we override the save, merge and persist methods to keep track of the Objects and its companyId. This way, when the object is persisted during the flush operation we get the original companyId and we set the CompanyThreadLocal to complete that operation.

Does it make sense to you? If so, I will try to have some ready for later today so you can check/complete the solution. In case we find a blocker or something we can contact Core Infra.

Thanks.

**Comment by mbowerman** [comment]
Hi @achaparro,

Yes, that sounds like a reasonable solution to me. Thanks!

**Comment by achaparro** [comment]
see https://github.com/mbowerman/liferay-portal/pull/153

**Pull request closed without merging**
