### PR TITLE
[TS] LPS-157041 Repeatable decimal fields are not indexable if one is an integer

### PR DESCRIPTION
**Pull request by javalosjr96**
Issue: 
When creating a repeating Double-type Numeric Structure , the form will throw ArrayStoreExpection errors if the user inputs a value without a decimal(10.0 vs 10).  Since the value doesn't have a decimal, it gets parsed as an Int, however when the DDMstructure is being indexed, it's elements are saved into a double-type array.

The removed code was added in order to remove the decimal from being displayed on the front-end.
@lr-cyun is testing to see if that is the only reason why that was added
[LPS-128822](https://issues.liferay.com/browse/LPS-128822)

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Does this change re-introduce [LPS-128822](https://issues.liferay.com/browse/LPS-128822)?

Another option to fix this would be to change [this line](https://github.com/liferay/liferay-portal/blob/5329fcdb461f56b6921a56252983255a7ab0076c/modules/apps/dynamic-data-mapping/dynamic-data-mapping-api/src/main/java/com/liferay/dynamic/data/mapping/storage/constants/FieldConstants.java#L191) to say:
```
return values.toArray(new Number[0]);
```

instead of 
```
return values.toArray(new Double[0]);
```

**Comment by javalosjr96** [comment]
@mbowerman 
Caleb tested it and it did not reintroduce the bug mentioned in [LPS-128822](https://issues.liferay.com/browse/LPS-128822).
I'll change it to see how it behaves.

**Comment by javalosjr96** [comment]
@mbowerman 
Hey Michael, 
I think it's better to move forward with your suggestion as it doesn't add a .0 to integers being used.  I'll update the PR and resubmit for testing.

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Pull request forwarded to the Forms team: https://github.com/liferay-forms/liferay-portal/pull/1846

**Pull request closed without merging**
