### PR TITLE
[TS] LPS-177032 Protobuf Vulnerability Detected in closure-compiler v20180204

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
[LPS-177032](https://issues.liferay.com/browse/LPS-177032)
Issue:
There is a protobuf component within this library that is being flagged by a customers third-party scanner(Dynatrace). 

 
Solution:
Update closure-compiler to v20220601 as protobuf no longer is in the library.

Notes:
Initially the solution was to update to the latest version, however due to library being deprecated for Java 8(only available on Java 11) we could not update it to the latest version.  v20220601 is the latest Java 8 version, but also does NOT contain protobuf which should cover this vulnerability.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
@mbowerman I resolved the SF, letting it finish relevant testing before pushing a change.

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
@mbowerman 
This fix failed on a 7.3 hotfix, I'll close this PR and resend when I resolve it.

**Pull request closed without merging**
