### PR TITLE
LPS-139554

### PR DESCRIPTION
**Pull request by javalosjr96**
@mbowerman 
Test BlogSharing#ShareWithUpdatePermissions has been modified for changes in full_content.jsp.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
@javalosjr96 The test failure [LocalFile.BlogsSharing#ShareWithCommentPermissions](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=6/6029//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_BlogsSharing_ShareWithCommentPermissions_) seems related too, can you look into it?

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
Reviewed and sent to Lima team for further review: https://github.com/liferay-lima/liferay-portal/pull/2314

**Pull request closed without merging**
