### PR TITLE
LPS-142093

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
@mbowerman 
Those failures are not relevant.

**Comment by mbowerman** [comment]
Pull request forwarded to the Echo team: https://github.com/liferay-echo/liferay-portal/pull/6353

**Pull request closed without merging**
