### PR TITLE
LPS-146807

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
https://issues.liferay.com/browse/LPS-146807

Issue:
Scheduled Articles continue to be displayed with scheduled filter when edited to be published

Cause:
The WHERE clause for Journal Status in the SQL query `findA_ByG_U_F_L` was not filtering results correctly.

Fix:
Use WHERE clause outside of other criteria for search. 

NOTE:
I checked out a failed test on my branch, I ran the test locally and it passed.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Hi @javalosjr96,

Could you please add a description to [LPS-146807](https://issues.liferay.com/browse/LPS-146807)?

**Comment by javalosjr96** [comment]
@mbowerman yes sorry

**Comment by javalosjr96** [comment]
@mbowerman updated

**Comment by javalosjr96** [comment]
@mbowerman 
I'm building a newer master to test the failure again.

**Comment by mbowerman** [comment]
Pull request forwarded to https://github.com/liferay-echo/liferay-portal/pull/7157. See my changes: https://github.com/liferay-echo/liferay-portal/compare/162fd7bb4f91d8cc5a17bdfb0b5d7bdb3d8c2a9e...4ca405b4a409c7916fb22603f85f1f414bc5e775

Also I noticed that if you click on **Filter and Order > Mine** in addition to **Filter and Order > Scheduled**, it calls a different Finder method which seems to exhibit a similar problem to `doFindF_A_ByG_F_L`. I'm not sure if that needs to be fixed as part of this ticket though, or if a different ticket can be opened for that.

**Pull request closed without merging**
