### PR TITLE
LPS-163136

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
https://issues.liferay.com/browse/LPS-163136

Issue:
A customer has recently flagged tika-core with https://github.com/advisories/GHSA-rpjm-422r-95mh.

Due to the connection with tika-parsers, tika-parsers will also have to be updated.

POI/POI-OOXML/POI-SCRATCHPAD were updated.
POI-OOXML-SCHEMAS was replaced by POI-OOXML-LITE.
XMLBEANS was updated as it was listed as a dependency. 

Solution:
Bump Tika to 1.28.5

### CODE REVIEW

**Comment by javalosjr96** [comment]
Only running ci:test:relevant as it takes 5 hours and running ci:test:sf will fail due to Bchan.

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
@mbowerman 
PR for SF failure:
https://github.com/brianchandotcom/liferay-portal/pull/125307

I'll run the source formatter as it should only fail due for the file above.

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
I'll check it out

**Comment by javalosjr96** [comment]
ci might be down again:
```
[beanshell] An error has occurred: java.lang.RuntimeException: java.net.NoRouteToHostException: No route to host (Host unreachable)
[beanshell] An error has occurred: java.lang.RuntimeException: java.net.NoRouteToHostException: No route to host (Host unreachable)
[beanshell] An error has occurred: java.lang.RuntimeException: java.net.NoRouteToHostException: No route to host (Host unreachable)
[beanshell] java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.NoRouteToHostException: No route to host (Host unreachable)
```

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci failures confirmed, affected server was blacklisted so the build should complete

**Comment by javalosjr96** [comment]
ci:reevaluate:1267401_5671

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
@mbowerman 
I'm checking out the failures,
I think a few are related.

**Comment by javalosjr96** [comment]
ci:reevaluate:1267401_5671

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:reevaluate:1267401_5671

**Comment by javalosjr96** [comment]
ci:reevaluate:1267401_5671

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
@mbowerman 
I resolved the failures that seem to be relevant, I just forgot a commit when I was rebasing.

The failures present don't seem to be related as I built a stock bundle and ran the same tests locally and they also failed.

**Comment by mbowerman** [comment]
Pull request forwarded to App Sec team: https://github.com/liferay-appsec/liferay-portal/pull/884

**Pull request closed without merging**
