### PR TITLE
LPS-190043 Create statement within concurrentProcess call

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket: [LPS-190043](https://liferay.atlassian.net/browse/LPS-190043)

Description:
When there is a data set affect by [LPS-181691](https://liferay.atlassian.net/browse/LPS-181691), then the nested Resultset will end up closing due to the capabilities of the Database type.   
e.g This occured once for me on MySQL 5.7, but none after.  

On Oracle19c this occurs frequently.

Solution:
Move the prepared statement so that a new one is created rather than reassigning parameters to the old one.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:upgrade

**Comment by javalosjr96** [comment]
@mbowerman 
I don't quite fully understand why the changes I made fixed the issue.  

Prior, these errors would be thrown:
Caused by: java.sql.SQLException: Closed Resultset: next
Different sources stated that the resultSet would be closed if the connection or statement is closed and the processConcurrently() could be closing the old statement, so a new one being opened for each resolved the issue?

Retesting on the latest master shortly.

**Comment by javalosjr96** [comment]
I tested on the latest master and the upgrade for Oracle completes after this change.

**Comment by mbowerman** [comment]
I agree, anyway to me it doesn't make sense to use the same PreparedStatement object in multiple simultaneously-run threads and setting the same parameters to different values in each thread (what we were doing before)...

**Comment by mbowerman** [comment]
Pull request forwarded to https://github.com/liferay-uniform/liferay-portal/pull/1276

**Pull request closed without merging**
