### PR TITLE
LPS-74635 Add to source formatter to allow line over 80 chars

### PR DESCRIPTION
**Pull request by jkappler**
Hi @mbowerman, 	@jonathanmccann. @ealonso is ooo, so we reviewed it with @pavel-savinov.

Please let us know what you think of the changes.

Thanks

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
Hey @jkappler, I don't really agree with these changes. Now you're computing hasPowerUserRole in some scenarios when you don't need to (for instance, when PropsValues.LAYOUT_USER_PRIVATE_LAYOUTS_POWER_USER_REQUIRED is false or PropsValues.LAYOUT_USER_PUBLIC_LAYOUTS_POWER_USER_REQUIRED is false), but the code is harder to read than when we started, and we had to add a line > 80 characters. There's an easy way to compute hasPowerUserRole at this frequency while still maintaining the exact same level of code readability as when we started. I'll send you another pull request shortly.

**Comment by mbowerman** [comment]
ci:stop

**Comment by jkappler** [comment]
ok @mbowerman, thanks

**Comment by mbowerman** [comment]
Resent at https://github.com/jkappler/liferay-portal/pull/41

**Pull request closed without merging**
