### PR TITLE
LPS-176295 Update Azure Core Libraries to 1.2.9

### PR DESCRIPTION
**Pull request by javalosjr96**
Issue:
If a customer is using Azure Cloud Services and has multiple pages, there is a chance that too many pages are fetched when a file is fetched.  This can cause the file to never to returned and performance issues.

Solution:
Update the Azure Core libraries; the bug was covered in a latest update.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
@javalosjr96 Could you check the failing AzureStoreSmoke test to see if it is related?

**Comment by javalosjr96** [comment]
@mbowerman 
On it.

**Comment by javalosjr96** [comment]
Running the test locally.

**Comment by javalosjr96** [comment]
@mbowerman 
This test fails locally as well.  It seems to be related to the bundle of failing Ci tests regarding:

`No results for path: $['companyId']`

I'll try to resolve this test in this PR,  locally, it fails during the teardown.

**Comment by javalosjr96** [comment]
@mbowerman 
I wasn't able to resolve that error as the performed a workaround when the issue initially occurred.  I performed the Azure Smoke Test Manually:
1. Upload Doc and Media TXT file.
2. Download uploaded TXT file. 
3. Delete TXT file

The portal didn't crash and the file was viewable/downloadable/removable from the Azure Storage.

**Comment by mbowerman** [comment]
Thanks @javalosjr96, seems the test may be broken right now, so I forwarded it to the Core Infrastructure team here: https://github.com/liferay-core-infra/liferay-portal/pull/3615

**Pull request closed without merging**
