### PR TITLE
LPS-143531

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @mbowerman 

i made the changes you suggested here:

https://issues.liferay.com/browse/LPS-135087?focusedCommentId=2578029&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2578029

Please review it, and forward it to the product team.

**Reproduction Steps:**

1. Set up a Liferay bundle
2. Go to Control Panel --> Content --> Web Content and add basic web content and add the following HTML in the source code of the content field:
<p>Hello This is the first line.</p>
 <p>Second line, it contain relative a <a href="/en/search">link</a> to search page.</p>
3. Publish the content.

**Actual Result:** The content is not published and the following error appears in the UI:

Error: Unable to validate referenced page with URL /en/search because the page group with URL /en cannot be found.
No errors in the log or browser console.

**Expected Result:** The web content should be published successfully with no errors.

Thanks, Roland

https://issues.liferay.com/browse/LPS-143531

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
Thanks @rolandpakai!

Pull request forwarded to Staging team: https://github.com/liferay-staging/liferay-portal/pull/18

See my changes: https://github.com/liferay-staging/liferay-portal/compare/f3f3bc8927d53b7ed426bd4c86c86c4c0537642c...e8ccd7b9025abb25912c10fa0523b876b7926816

**Comment by rolandpakai** [comment]
Thank you @mbowerman

**Pull request closed without merging**
