### PR TITLE
LPS 138676

### PR DESCRIPTION
**Pull request by javalosjr96**
Fixed the Logic in isRootFolder method and added the parent folder title back to the DocBar in Documents and Media.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Hi @javalosjr96,

This looks good to me! I'm going to wait for the test suite to run, then I'll forward it onto the product team if there don't appear to be any relevant test failures.

**Comment by mbowerman** [comment]
Hi @javalosjr96,

It looks like there was a source formatting failure on the pull request. As a reminder, please be sure to run the Source Formatter prior to sending pull requests.

In this instance, the issue wasn't something that the Source Formatter could fix automatically, so you'll need to also remember to check the output from the Source Formatter to see if there are any changes that need to be made.

The failure was:
```
Method 'Validator.isNotNull' should only be used for type 'Long', 'Serializable' or 'String'
```
Explanation: The `Validator.isNotNull` method is only intended to be used on certain types of objects (Long, Serializable, String). For most other objects, you should just use `!= null` instead (e.g. `parentFolder != null`)

I'm going to close this pull request for now. Please feel free to re-send the pull request once you have fixed the source formatting error. Thanks!

**Comment by javalosjr96** [comment]
@mbowerman 
Thanks for reviewing.
I'll make the changes and upload shortly.

**Pull request closed without merging**
