### PR TITLE
LPS-73051

### PR DESCRIPTION
**Pull request by holatuwol**
This will not work on all databases if we lack the correct SQLTransformerLogic for CAST_LONG for any of the databases, so let's see if our upgrade tests work.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:stop

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
ci:reopen

**Comment by holatuwol** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/49652

**Comment by mbowerman** [comment]
ci:retest

**Comment by mbowerman** [comment]
@holatuwol These test failures look relevant, although what's surprising is that even the MySQL tests are failing the UpgradeResourcePermissionTest.

**Pull request closed without merging**
