### PR TITLE
LPS 137424v2

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:sf
ci:test:relevant

**Comment by mbowerman** [comment]
Reviewed and sent to Echo team for further review: https://github.com/liferay-echo/liferay-portal/pull/5815

**Pull request closed without merging**
