### PR TITLE
LPS-141974 Localized FriendlyURLs should also check for duplicates when being created

### PR DESCRIPTION
**Pull request by javalosjr96**

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
@mbowerman 
I would like to rebuild a new master and test for this issue.

**Comment by javalosjr96** [comment]
@mbowerman 
Sorry for the delay in the update.
The issue is not reproducible with the fix.

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Pull request forwarded to https://github.com/liferay-echo/liferay-portal/pull/6375.

See my changes: https://github.com/liferay-echo/liferay-portal/pull/6375/commits/d3cadb44bd8a4b8a9555310130dcad587d4247e9

I made a change to add back in the old methods `getFriendlyURL(long, boolean, long, String, String)` and `validateFriendlyURL(long, boolean, long, String, String)` since they are public methods and we don't want to break custom code that is calling them.

**Pull request closed without merging**
