### PR TITLE
Lps 152875

### PR DESCRIPTION
**Pull request by javalosjr96**
Ticket:
https://issues.liferay.com/browse/LPS-152875?filter=-1

Issue:
There is a DoS vulerability in the current version of org.json:json.

Solution:
Update org.json:json to v2022032.

### CODE REVIEW

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by javalosjr96** [comment]
ci:test:sf

**Comment by javalosjr96** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
I think the SF error is probably a regression of https://github.com/liferay/liferay-portal/commit/608dd4ca8a08f760ae9946745f3152aaa3ef72fe

**Comment by mbowerman** [comment]
I sent a pull request to fix the SF error here: https://github.com/brianchandotcom/liferay-portal/pull/116984

**Comment by mbowerman** [comment]
Pull request forwarded to https://github.com/liferay-core-infra/liferay-portal/pull/726.

There were a few JSON test failures on one of the test runs, but I don't believe that they're related because they were only occurring on one of the runs.

**Pull request closed without merging**
